// <auto-generated />
using System;
using FinderLink.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinderLink.Migrations
{
    [DbContext(typeof(FinderLinkDbContext))]
    [Migration("20260510045600_AddLocationService")]
    partial class AddLocationService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinderLink.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("FinderLink.Models.AdminLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("LogId");

                    b.HasIndex("AdminId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LogDate");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("FinderLink.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("ClaimDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ClaimerContact")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ClaimerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("DateClaimed")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateVerified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("VerifiedBy")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("AdminId");

                    b.HasIndex("ItemId");

                    b.HasIndex("Status");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("FinderLink.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFound")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("FoundByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("FoundByContact")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FoundByName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LocationFound")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ItemId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DateFound");

                    b.HasIndex("FoundByAdminId");

                    b.HasIndex("Status");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FinderLink.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("FinderLink.Models.Release", b =>
                {
                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReleaseId"));

                    b.Property<int?>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Proof")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReleasedBy")
                        .HasColumnType("int");

                    b.Property<int>("ReleasedTo")
                        .HasColumnType("int");

                    b.HasKey("ReleaseId");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.HasIndex("ItemId");

                    b.HasIndex("ReleasedBy");

                    b.HasIndex("ReleasedTo");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("FinderLink.Models.AdminLog", b =>
                {
                    b.HasOne("FinderLink.Models.Admin", "Admin")
                        .WithMany("AdminLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinderLink.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId");

                    b.HasOne("FinderLink.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Admin");

                    b.Navigation("Claim");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FinderLink.Models.Claim", b =>
                {
                    b.HasOne("FinderLink.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinderLink.Models.Item", "Item")
                        .WithMany("Claims")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinderLink.Models.Admin", "VerifiedByAdmin")
                        .WithMany("ClaimsVerified")
                        .HasForeignKey("VerifiedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Admin");

                    b.Navigation("Item");

                    b.Navigation("VerifiedByAdmin");
                });

            modelBuilder.Entity("FinderLink.Models.Item", b =>
                {
                    b.HasOne("FinderLink.Models.Admin", "CreatedByAdmin")
                        .WithMany("ItemsCreated")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinderLink.Models.Admin", "FoundByAdmin")
                        .WithMany("ItemsFound")
                        .HasForeignKey("FoundByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("FoundByAdmin");
                });

            modelBuilder.Entity("FinderLink.Models.Release", b =>
                {
                    b.HasOne("FinderLink.Models.Claim", "Claim")
                        .WithOne("Release")
                        .HasForeignKey("FinderLink.Models.Release", "ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinderLink.Models.Item", "Item")
                        .WithMany("Releases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinderLink.Models.Admin", "ReleasedByAdmin")
                        .WithMany("ReleasedItems")
                        .HasForeignKey("ReleasedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FinderLink.Models.Admin", "ReleasedToAdmin")
                        .WithMany("ReceivedReleases")
                        .HasForeignKey("ReleasedTo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Item");

                    b.Navigation("ReleasedByAdmin");

                    b.Navigation("ReleasedToAdmin");
                });

            modelBuilder.Entity("FinderLink.Models.Admin", b =>
                {
                    b.Navigation("AdminLogs");

                    b.Navigation("ClaimsVerified");

                    b.Navigation("ItemsCreated");

                    b.Navigation("ItemsFound");

                    b.Navigation("ReceivedReleases");

                    b.Navigation("ReleasedItems");
                });

            modelBuilder.Entity("FinderLink.Models.Claim", b =>
                {
                    b.Navigation("Release");
                });

            modelBuilder.Entity("FinderLink.Models.Item", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
